language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - echo -e "Host ec2-54-204-7-85.compute-1.amazonaws.com\n\tStrictHostKeyChecking no\nUser ubuntu\nIdentityFile .travis/acton.pem" >> ~/.ssh/config
script:
  - 'grunt'
after_success:
  - chmod 600 .travis/acton.pem # this key should have push access
  - ssh-add .travis/acton.pem
  - git remote add deploy 'ec2-54-204-7-85.compute-1.amazonaws.com:/home/ubuntu/wampumfrontend.git'
  - git push deploy